version: '3.1'

services:

  benote:
    container_name: benote
    build: benote/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_PASSWORD: 15243
      POSTGRES_USER: roman
      POSTGRES_DB: maindb
      PGDATA: C:\Documents\Пользователи\Роман\maindbdata
      POSTGRES_INITDB_ARGS: "-A md5"


