# Generated by Django 4.2.1 on 2023-07-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_basket_model_alter_content_last_time_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Задача')),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
    ]
