# Generated by Django 4.2.3 on 2023-07-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tasks_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_model',
            name='title',
            field=models.CharField(max_length=5, verbose_name='Название записки'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=5, verbose_name=''),
        ),
    ]
