# Generated by Django 4.2.3 on 2023-08-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_basket_model_title_alter_content_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_model',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название записки'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=60, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tasks_model',
            name='text',
            field=models.CharField(max_length=110, verbose_name='Задача'),
        ),
    ]
